package com.statestreet.referencerate;

/**
 * Created by mateusdasilva on 08/05/2016.
 */
public enum PriceProvider {
    PROVIDER1,
    PROVIDER2,
    PROVIDER3,
    PROVIDER4,
    PROVIDER5,
    PROVIDER6,
    PROVIDER7,
    PROVIDER8,
    PROVIDER9,
    PROVIDER10,
    PROVIDER11,
    PROVIDER12,
    PROVIDER13,
    PROVIDER14,
    PROVIDER15,
    PROVIDER16,
    PROVIDER17,
    PROVIDER18,
    PROVIDER19,
    PROVIDER20,
    PROVIDER21,
    PROVIDER22,
    PROVIDER23,
    PROVIDER24,
    PROVIDER25,
    PROVIDER26,
    PROVIDER27,
    PROVIDER28,
    PROVIDER29,
    PROVIDER30,
}
